### ISSUE TITLE
[Info] 브랜치 네이밍 규칙

### ISSUE THREAD

**Issue by ehdcjf4874** [Algorithm-Book/Algorithm-Book.github.io#1]
# Branch 생성 방법

## master branch
제품으로 출시될 수 있는 브랜치

## develop branch
- develop/<Issue_number> or <develop_name>/ Short Description

다음 출시 버전을 개발하는 브랜치
기능 개발을 위한 브랜치들을 병합하기 위해 사용한다.
즉, 모든 기능이 추가되고 버그가 수정되어 배포 가능한 안정적인 사태라면 develop 브랜치를 master 브랜치에 merge(병합)한다.
평소에는 이 브랜치를 기반으로 개발을 진행한다.

## Feature branch
- Feature/<Issue_number> or <Feature_name>/ Short Description

기능을 개발하는 브랜치 (Local)
feature 브랜치는 새로운 기능 개발 및 버그 수정이 필요할 때마다 ‘develop’ 브랜치로부터 분기합니다. feature 브랜치에서의 작업은 기본적으로 공유할 필요가 없기 때문에, 주로 자신의 로컬 저장소에서 관리합니다. 
@CoffeeShelter @tlans21

**Comment by CoffeeShelter** [comment]
해당 내용은 이슈가 아니라 Wiki에 작성하는 것이 괜찮을 거 같아요

**Comment by ehdcjf4874** [comment]
WiKi가 유료라서 사용할 수 없습니다
<수정> 알아보니 WiK무료로 사용가능합니다.

**Comment by ehdcjf4874** [comment]
WIKI로 옮겼으므로 닫겠습니다.
