### ISSUE TITLE
[Info] 강력 새로고침은 되지만 새로고침은 안되는 오류 해결 

### ISSUE THREAD

**Issue by ehdcjf4874** [Algorithm-Book/Algorithm-Book.github.io#35]
문제: 잔여 캐시 정보가 있어 삭제된 경로 파일을 실행하려고 하여 오류 발생

해결방법: 캐시 및 쿠키 삭제

Chrome의 경우
1. 컴퓨터에서 Chrome을 엽니다.
2. 오른쪽 상단에서 더보기 더보기를 클릭합니다.
3. 도구 더보기 다음 인터넷 사용 기록 삭제를 클릭합니다.
4. 상단에서 기간을 선택합니다. 모든 항목을 삭제하려면 전체를 선택합니다.
5. '쿠키 및 기타 사이트 데이터'와 '캐시된 이미지 또는 파일' 옆의 체크박스를 선택합니다.
6. 인터넷 사용 기록 삭제를 클릭합니다.

**Comment by CoffeeShelter** [comment]
```Ctrl``` + ```F5``` 강력 새로고침 단축키 입니다. (캐시 데이터 삭제)

**Comment by ehdcjf4874** [comment]
해결됐으므로 이슈 닫겠습니다.
