### ISSUE TITLE
알고리즘 난이도 분류

### ISSUE THREAD

**Issue by ehdcjf4874** [Algorithm-Book/Algorithm-Book.github.io#4]
https://solved.ac/problems/level를 참고하여 알고리즘 난이도를 분류할 때,
어떤 기준으로 분류해야 할까요?
@CoffeeShelter @tlans21

**Comment by tlans21** [comment]
개개인이 느끼기에 따라 문제가 쉬울 수도 있고 어려울 수도 있다고 느끼실 수 있습니다.
그래서 여러 사람들이 모여서 난이도 평가를 할 수 있는 solved.ac 사이트에서 기준을 잡아
문제 별 난이도에 맞춰 분류할 생각입니다. 

보통 알고리즘을 공부하는 목적은 기업의 코딩 테스트를 통과입니다.
solved.ac가 설정한 문제 난이도 개념이  브론즈,  실버,  골드, 플래티넘 등입니다.

알아본 바 코딩 테스트가 브론즈~골드 난이도로 거의 대부분이 출제됩니다.
그렇기 때문에  목적에 맞게 골드,실버 브론즈 문제를 난이도 각각 상, 중, 하로 설정하는게 어떨까합니다.

알고리즘 난이도 분류는 
알고리즘을 만들기 위한 자료구조 개념들이 많이 사용되는가?
코드의 길이가 많이 사용되는가?
등등
 
여러가지 상황들을 상정하여 저희 프로젝트 팀원 3명이 투표 하에 초급, 중급, 고급으로 나눠볼 생각입니다.

**Comment by ehdcjf4874** [comment]
'골드,실버 브론즈 문제를 난이도 각각 상, 중, 하로 설정' 하는 부분 동의합니다.

**Comment by ehdcjf4874** [comment]
질문 해결하여 닫겠습니다.
