### ISSUE TITLE
[Todo] 문서 작업

### ISSUE THREAD

**Issue by CoffeeShelter** [Algorithm-Book/Algorithm-Book.github.io#41]
할일
-----
- [x] ```README.md``` 파일 수정

**Comment by CoffeeShelter** [comment]
@ehdcjf4874 @ehdcjf4874 
[리드미 파일](https://github.com/Algorithm-Book/Algorithm-Book.github.io/tree/41-todo-doc) 확인 부탁드립니다.

**Comment by ehdcjf4874** [comment]
확인했습니다! 이슈만드실때 네이밍 규칙에 맞춰 주시면 감사하겠습니다.
제가 일단 수정했습니다.
@CoffeeShelter

**Comment by CoffeeShelter** [comment]
넵 네이밍 규칙 확인하겠습니다.
